Add certificate status dashboard
SUSE/caasp-monitoring pull request #7
Opened 2020-04-17 04:40 UTC by jenting

2020-04-23 03:49 UTC, innobead commented
Waiting for further study about how to add aggregated info instead of time series data.

2020-04-23 06:30 UTC, jenting commented
> Waiting for further study about how to add aggregated info instead of time series data.

Done! PTAL :bow:

2020-05-04 03:29 UTC, maximenoel8 submitted a review, later dismissed
Working fine for me

2020-05-04 04:13 UTC, innobead requested changes
LGTM. Minor request to resolve.

2020-05-04 04:13 UTC, innobead commented on README.md
> +Then we need to manually setup extra configuration to Prometheus server. The etcd server expose metrics on `/metrics` endpoint, the Prometheus jobs does not scrapes it by default. We need to add a ne
```suggestion
Then we need to manually set up extra configuration to Prometheus server. The etcd server exposes metrics on `/metrics` endpoint, the Prometheus jobs do not scrape it by default. We need to add a new job to Prometheus configmap to scapes metrics from the etcd cluster. Also since the etcd cluster run in https, we need the etcd client certificate in order to access the `/metrics` endpoint.
```

2020-05-04 05:38 UTC, innobead approved these changes

2020-06-11 02:38 UTC, cclhsu approved these changes

2020-06-11 02:38 UTC, merged